

# # Set environment variables
# ENV PYTHONPATH=/app/src


FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

#  Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 50053

# Run the gRPC server
CMD ["python", "-m", "src.book_server"]
