version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../layered-architecture
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/library
      depends_on:
        - db
      ports:
        - "5000:5000"
  
  frontend:
    build: ../frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: