# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"O\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04isbn\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"=\n\x0e\x41\x64\x64\x42ookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04isbn\x18\x03 \x01(\t\"+\n\x0f\x41\x64\x64\x42ookResponse\x12\x18\n\x04\x62ook\x18\x01 \x01(\x0b\x32\n.book.Book\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\t\"+\n\x0fGetBookResponse\x12\x18\n\x04\x62ook\x18\x01 \x01(\x0b\x32\n.book.Book\"\x12\n\x10ListBooksRequest\".\n\x11ListBooksResponse\x12\x19\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\n.book.Book\"5\n\x17UpdateBookStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"4\n\x18UpdateBookStatusResponse\x12\x18\n\x04\x62ook\x18\x01 \x01(\x0b\x32\n.book.Book2\x8e\x02\n\x0b\x42ookService\x12\x36\n\x07\x41\x64\x64\x42ook\x12\x14.book.AddBookRequest\x1a\x15.book.AddBookResponse\x12\x36\n\x07GetBook\x12\x14.book.GetBookRequest\x1a\x15.book.GetBookResponse\x12<\n\tListBooks\x12\x16.book.ListBooksRequest\x1a\x17.book.ListBooksResponse\x12Q\n\x10UpdateBookStatus\x12\x1d.book.UpdateBookStatusRequest\x1a\x1e.book.UpdateBookStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=20
  _globals['_BOOK']._serialized_end=99
  _globals['_ADDBOOKREQUEST']._serialized_start=101
  _globals['_ADDBOOKREQUEST']._serialized_end=162
  _globals['_ADDBOOKRESPONSE']._serialized_start=164
  _globals['_ADDBOOKRESPONSE']._serialized_end=207
  _globals['_GETBOOKREQUEST']._serialized_start=209
  _globals['_GETBOOKREQUEST']._serialized_end=237
  _globals['_GETBOOKRESPONSE']._serialized_start=239
  _globals['_GETBOOKRESPONSE']._serialized_end=282
  _globals['_LISTBOOKSREQUEST']._serialized_start=284
  _globals['_LISTBOOKSREQUEST']._serialized_end=302
  _globals['_LISTBOOKSRESPONSE']._serialized_start=304
  _globals['_LISTBOOKSRESPONSE']._serialized_end=350
  _globals['_UPDATEBOOKSTATUSREQUEST']._serialized_start=352
  _globals['_UPDATEBOOKSTATUSREQUEST']._serialized_end=405
  _globals['_UPDATEBOOKSTATUSRESPONSE']._serialized_start=407
  _globals['_UPDATEBOOKSTATUSRESPONSE']._serialized_end=459
  _globals['_BOOKSERVICE']._serialized_start=462
  _globals['_BOOKSERVICE']._serialized_end=732
# @@protoc_insertion_point(module_scope)
