# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import borrowing_pb2 as borrowing__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in borrowing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BorrowingServiceStub(object):
    """Borrowing service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BorrowBook = channel.unary_unary(
                '/borrowing.BorrowingService/BorrowBook',
                request_serializer=borrowing__pb2.BorrowRequest.SerializeToString,
                response_deserializer=borrowing__pb2.BorrowResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/borrowing.BorrowingService/ReturnBook',
                request_serializer=borrowing__pb2.ReturnRequest.SerializeToString,
                response_deserializer=borrowing__pb2.ReturnResponse.FromString,
                _registered_method=True)
        self.GetBorrowedBooks = channel.unary_unary(
                '/borrowing.BorrowingService/GetBorrowedBooks',
                request_serializer=borrowing__pb2.UserRequest.SerializeToString,
                response_deserializer=borrowing__pb2.BorrowedBooksResponse.FromString,
                _registered_method=True)


class BorrowingServiceServicer(object):
    """Borrowing service definition
    """

    def BorrowBook(self, request, context):
        """Borrow a book
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Return a book
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBorrowedBooks(self, request, context):
        """Get a user's borrowed books
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BorrowingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=borrowing__pb2.BorrowRequest.FromString,
                    response_serializer=borrowing__pb2.BorrowResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=borrowing__pb2.ReturnRequest.FromString,
                    response_serializer=borrowing__pb2.ReturnResponse.SerializeToString,
            ),
            'GetBorrowedBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBorrowedBooks,
                    request_deserializer=borrowing__pb2.UserRequest.FromString,
                    response_serializer=borrowing__pb2.BorrowedBooksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'borrowing.BorrowingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('borrowing.BorrowingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BorrowingService(object):
    """Borrowing service definition
    """

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowing.BorrowingService/BorrowBook',
            borrowing__pb2.BorrowRequest.SerializeToString,
            borrowing__pb2.BorrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowing.BorrowingService/ReturnBook',
            borrowing__pb2.ReturnRequest.SerializeToString,
            borrowing__pb2.ReturnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBorrowedBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowing.BorrowingService/GetBorrowedBooks',
            borrowing__pb2.UserRequest.SerializeToString,
            borrowing__pb2.BorrowedBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
