# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x8b\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nstudent_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x15\n\rpassword_hash\x18\x05 \x01(\t\x12!\n\tuser_type\x18\x06 \x01(\x0e\x32\x0e.user.UserType\x12\x0c\n\x04role\x18\x07 \x01(\t\"e\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12!\n\tuser_type\x18\x04 \x01(\x0e\x32\x0e.user.UserType\".\n\x12\x43reateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"+\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"-\n\x17\x41uthenticateUserRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\"E\n\x18\x41uthenticateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x12\n\x10ListUsersRequest\".\n\x11ListUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User*/\n\x08UserType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07STUDENT\x10\x01\x12\t\n\x05STAFF\x10\x02\x32\x97\x02\n\x0bUserService\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12Q\n\x10\x41uthenticateUser\x12\x1d.user.AuthenticateUserRequest\x1a\x1e.user.AuthenticateUserResponse\x12<\n\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERTYPE']._serialized_start=574
  _globals['_USERTYPE']._serialized_end=621
  _globals['_USER']._serialized_start=21
  _globals['_USER']._serialized_end=160
  _globals['_CREATEUSERREQUEST']._serialized_start=162
  _globals['_CREATEUSERREQUEST']._serialized_end=263
  _globals['_CREATEUSERRESPONSE']._serialized_start=265
  _globals['_CREATEUSERRESPONSE']._serialized_end=311
  _globals['_GETUSERREQUEST']._serialized_start=313
  _globals['_GETUSERREQUEST']._serialized_end=341
  _globals['_GETUSERRESPONSE']._serialized_start=343
  _globals['_GETUSERRESPONSE']._serialized_end=386
  _globals['_AUTHENTICATEUSERREQUEST']._serialized_start=388
  _globals['_AUTHENTICATEUSERREQUEST']._serialized_end=433
  _globals['_AUTHENTICATEUSERRESPONSE']._serialized_start=435
  _globals['_AUTHENTICATEUSERRESPONSE']._serialized_end=504
  _globals['_LISTUSERSREQUEST']._serialized_start=506
  _globals['_LISTUSERSREQUEST']._serialized_end=524
  _globals['_LISTUSERSRESPONSE']._serialized_start=526
  _globals['_LISTUSERSRESPONSE']._serialized_end=572
  _globals['_USERSERVICE']._serialized_start=624
  _globals['_USERSERVICE']._serialized_end=903
# @@protoc_insertion_point(module_scope)
